scene:
  built_in: true
  name: munich
  transmitter_array:
    num_rows: 1
    num_cols: 7
    vertical_spacing: 0.5
    horizontal_spacing: 0.5
    pattern: tr38901
    polarization: V
  receiver_array:
    num_rows: 1
    num_cols: 1
    vertical_spacing: 0.5
    horizontal_spacing: 0.5
    pattern: dipole
    polarization: V
  transmitter:
    name: tx
    position: [46, -47, 80]
    orientation: [0.0, 90, 0]
  receiver:
    name: rx
    position: [-180, -30, 1.5]
    orientation: [0.0, 0, 0]
  camera:
    position: [0, 0, 1300]
    look_at: [0, 0, 0]


algorithm:
  custom_algorithm: none
  name: pso  # or choose ga
  params:
    population_size: 50
    max_generations: 30 # 100 for ga
    w: 0.5
    c1: 1.5
    c2: 1.5
    stagnant_limit: 20
    seed_particle: [0, 0]
    angle_unit: degree
    num_cols: 16
    num_rows: 1
    mutation_rate: 0.7
    crossover_rate: 0.5
    search_limit: 40
    angle_bounds: [[0, 90], [0, 360]]
    resolution: 0.5
    elite_count: 3








