scene:
  built_in: true
  name: munich
  transmitter_array:
    num_rows: 1
    num_cols: 7
    vertical_spacing: 0.5
    horizontal_spacing: 0.5
    pattern: tr38901
    polarization: V
  receiver_array:
    num_rows: 1
    num_cols: 1
    vertical_spacing: 0.5
    horizontal_spacing: 0.5
    pattern: dipole
    polarization: V
  transmitter:
    name: tx
    position: [46, -47, 80]
    orientation: [0.0, 90, 0]
  receiver:
    name: rx
    position: [-180, -30, 1.5]
    orientation: [0.0, 0, 0]
  camera:
    position: [0, 0, 1300]
    look_at: [0, 0, 0]


algorithm:
  custom_algorithm:none
  name:none





